import { ConnectButton } from '@rainbow-me/rainbowkit';
import { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Button } from '@web3uikit/core';
import Link from 'next/link';
import { Router, useRouter } from 'next/router';


const Home = () => {
	const router = useRouter();

	return (
		<div className={styles.container}>
			<Head>
				<title>Carpet Finance</title>
				<meta
					name="description"
					content="Generated by @rainbow-me/create-rainbowkit"
				/>
				<link rel="icon" href="/favicon.png" />
			</Head>
			<div className={styles.container}>
				<Button
					color="blue"
					theme="colored"
					onClick={() => router.push('/application')}
					text="Enter App" />
			</div>
		</div>
	);
};

export default Home;
